spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/tasks/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

